name: Print Test on Push

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print test and exit
        run: |
          echo "test"
          exit 0
